name: Contribute

on:
  issues:
    types: [opened]

jobs:
  add:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.issue.body, '## Map Contribution') }}
    steps:
      - uses: actions/checkout@v4
      - run: echo "Checked out"
