name: Contribute

on:
  issues:
    types: [opened]

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Issue has Map Contribution: ${{ contains(github.event.issue.body, '## Map Contribution') }}"
